#version 460 core
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba8) uniform writeonly image2D uColorBuffer;
uniform ivec2 uResolution;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (pixel.x >= uResolution.x || pixel.y >= uResolution.y) return;

    //float col = float(pixel.x % 2) * float((pixel.y + 1) % 2) * 0.3;
    float col = 0.f;
    imageStore(uColorBuffer, pixel, vec4(vec3(col), 1.0));
}
